
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gntzqfuirtoijagfissh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdudHpxZnVpcnRvaWphZ2Zpc3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTE4OTEsImV4cCI6MjA1Nzc2Nzg5MX0.JpuBYE8VRnlWz--BT0RC4ES5ctMH-OTq5dU16fVve9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
